import './globals.css'
import Navbar from '../components/Navbar'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={roboto.className}>
        <Navbar/>

        {children}
      </body>
    </html>
  )
}
